### ISSUE TITLE
What is the difference between sprunge.us and ix.io?

### ISSUE THREAD

**Issue by franciscolourenco** [rupa/sprunge#10]
Besides the obvious diference in the domain name and some small differences in the url scheme, is there any other diference between them?

Thanks

**Comment by rupa** [comment]
sprunge runs on app engine, ix is on my server, and has a few more features.

**Comment by franciscolourenco** [comment]
Thank you

**Comment by SRGOM** [comment]
Does it use the same code? Or is it closed?
