### ISSUE TITLE
500 Internal Server Error on sprunge.us

### ISSUE THREAD

**Issue by gboudreau** [rupa/sprunge#19]
Trying to use sprunge.us results in the following error:

```
500 Internal Server Error
The server has either erred or is incapable of performing the requested operation.
```

Both from a command line, or using the online form to paste something.

**Comment by rupa** [comment]
Thanks. It's exceeded its resource limits - I'll see what I can do. In the
meantime http://ix.io is nice :)

**Comment by martafolf** [comment]
Seems fixed as far as I can tell. - Is ix.io also one of your creations ? I like sprunge more, its more simplistic, has IPv6 support. Just lacks proper protection, I discovered pasting the same thing 100 times works, and it shouldn't, also, perhaps give people a definite limit to paste expiration, such as a day or a week, and not just wait for it to run out of space to clear the old ones. :)

**Comment by gboudreau** [comment]
Indeed, working now. And thanks for the alternative. I also coded my own, using the pastebin API, just in call all hell breaks loose, and I need a quick drop-in replacement.
