### ISSUE TITLE
http://ix.io/user/fs gives an HTTP 500 error

### ISSUE THREAD

**Issue by kini** [rupa/sprunge#28]
As title.

**Comment by brycied00d** [comment]
So? What does that site have to do with http://sprunge.us and its codebase?

**Comment by kini** [comment]
ix.io is running on a derivative of sprunge.us -- see #10. There's no issue tracker for ix.io so I'm reporting the issue here. Hopefully this is OK with @rupa.

**Comment by brycied00d** [comment]
Ah, I had no idea, I'm sorry for my rudeness.
I just tried the URL and it loads fine, HTTP response code 200.

**Comment by kini** [comment]
Uh... you're right. WFM now too. It had been broken the last 5-10 times I tried it over the last several weeks, so I have no idea why it suddenly works... Well, I guess all it took was someone else looking at it (?).

Closing since I can no longer reproduce.
