### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by franciscolourenco** [rupa/sprunge#8]
I love the simplicity of the pastes. 
Would it be possible to have syntax highlighting depending on the extension?

For example http://sprunge.us/YdQb would be plain while http://sprunge.us/YUQb.py would have python syntax highlighting.

http://hastebin.com/ has this feature unfortunately the default urls don't have a default non-javascript version which makes it broken from people who use no-script or similar

**Comment by untitaker** [comment]
`http://sprunge.us/YdQb?py`

**Comment by franciscolourenco** [comment]
Thanks
